# Generated by Django 5.2.8 on 2025-12-01 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Hotel Name')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price per Night')),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Rating')),
                ('status', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='Status')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='hotels/', verbose_name='Main Image')),
                ('gallery', models.JSONField(blank=True, null=True, verbose_name='Gallery Images')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
                'db_table': 'hotels',
                'ordering': ['-created_at'],
            },
        ),
    ]
