# Generated by Django 5.2.8 on 2025-12-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='gallery',
        ),
        migrations.RemoveField(
            model_name='hotel',
            name='status',
        ),
        migrations.AddField(
            model_name='hotel',
            name='available_rooms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_breakfast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_parking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='has_wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hotel',
            name='is_available',
            field=models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True, verbose_name='Is Available'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='hotels/images/', verbose_name='Main Image'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=2),
        ),
    ]
