# Generated by Django 5.2.8 on 2025-12-01 10:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(max_length=100)),
                ('force_update', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('description', models.TextField(default='')),
                ('device_type', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('ALL', 'ALL')], db_index=True, default='ALL', max_length=7)),
            ],
            options={
                'verbose_name': 'app version',
                'verbose_name_plural': 'app versions',
                'db_table': 'appversion',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_model', models.CharField(db_index=True, max_length=255)),
                ('operation_version', models.CharField(max_length=155)),
                ('device_type', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('ALL', 'ALL')], db_index=True, default='ANDROID', max_length=7)),
                ('device_id', models.CharField(db_index=True, help_text='Unique device identifier', max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the device', validators=[django.core.validators.validate_ipv46_address])),
                ('last_login', models.DateTimeField(auto_now=True, db_index=True)),
                ('first_login', models.DateTimeField(auto_now_add=True)),
                ('visit_location', models.JSONField(blank=True, help_text='Geographic location data', null=True)),
                ('language', models.CharField(choices=[('RU', 'Russian'), ('EN', 'English'), ('CRL', 'Cyrillic'), ('UZ', 'Uzbek')], default='CRL', max_length=3)),
                ('theme', models.CharField(choices=[('DARK', 'Dark'), ('LIGHT', 'Light')], default='LIGHT', max_length=5)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Device session is active')),
                ('is_push_notification', models.BooleanField(default=True, verbose_name='Push Notifications Enabled')),
                ('is_auth_password', models.BooleanField(default=False, verbose_name='Biometric Authentication Enabled')),
                ('device_token', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('logged_out_at', models.DateTimeField(blank=True, help_text='When user logged out from this device', null=True)),
                ('firebase_token', models.CharField(blank=True, db_index=True, max_length=500, null=True, unique=True)),
                ('app_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='users.appversion')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device',
                'verbose_name_plural': 'Devices',
                'db_table': 'devices',
                'ordering': ['-last_login'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='device_user_active_idx'), models.Index(fields=['device_id', 'device_type'], name='device_id_type_idx'), models.Index(fields=['-last_login'], name='device_last_login_idx')],
            },
        ),
    ]
