# Generated by Django 5.2.8 on 2025-12-01 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excursion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('duration_hours', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='excursions/images/')),
                ('is_available', models.BooleanField(choices=[(True, 'Active'), (False, 'Inactive')], default=True)),
            ],
            options={
                'verbose_name': 'Excursion',
                'verbose_name_plural': 'Excursions',
                'ordering': ['title'],
            },
        ),
    ]
